#!/bin/bash
# Stage the Python import closure to node-local storage, so that startup does
# not read module bytes off /lus/flare.
#
# WHY
# ---
# Job 8742027's rung 1 never reached iteration 0. All 12 ranks of node 1 dumped
# the same stack: importlib._bootstrap_external:1191 `get_data` -- reading a
# module's bytes -- inside site-packages/torchvision/datasets/__init__.py.
# `init_process_group backend=xccl world_size=24` had already logged 2 s in, so
# this was not rendezvous, not xccl and not the fabric. It was Python import
# blocked on Lustre, and it burned the 900 s watchdog deadline and the rung.
#
# The healthy case is not free either: measured on four arms, the interval from
# scaffold's "Running pre-training of app" to the trainer's first log line is
# 45 / 39 / 51 / 53 s. Every rung pays ~45 s before it does any work.
#
# WHAT IS STAGED, AND WHY WHOLE PACKAGES
# --------------------------------------
# The 40 top-level packages the trainer import touches: 4.5 GB, dominated by
# triton (2.6 GB) and torch (1.5 GB). NOT all of site-packages (5.2 GB), and NOT
# a per-file manifest of the import closure -- that was tried first and failed
# twice, and the second failure is why this copies whole packages:
#
#   1. `libscipy_openblas64_-...so: cannot open shared object file`. sys.modules
#      names an extension module, never the libraries it dlopens via RPATH.
#      Reading /proc/self/maps after the import fixed that particular miss.
#   2. `Unable to find torch_shm_manager at .../torch/bin/`. A plain BINARY --
#      not a module, not a mapped library. No introspection of a running import
#      can see it.
#
# (2) is not a patchable gap; a package may reference any data file at runtime.
# What makes package granularity safe is the sys.path fallback:
#
#   the staged tree is PREPENDED, with the Lustre venv still behind it. A
#   package ABSENT from the staged tree resolves to Lustre -- correct, just
#   slow. A package PRESENT but internally incomplete is found first and then
#   fails on the missing file.
#
# So partial-at-package-granularity is safe; partial-at-file-granularity is not.
#
# /tmp IS RAM ([[aurora-tmp-is-tmpfs]]). 4.5 GB/node against ~1 TB is affordable
# but not free -- it competes with page cache, which the dataload tail work has
# shown matters. Staging the imported packages rather than the whole tree is the
# compromise; if RAM pressure ever shows up, drop `triton` first (2.6 GB, and
# torch.compile is not viable on XPU anyway).
#
# FAILING SAFE IS THE POINT
# -------------------------
#   - stage to a temp dir, verify by ACTUALLY IMPORTING through it, and only
#     then publish by rename()
#   - on ANY failure, print why and exit 0 WITHOUT publishing. The caller keeps
#     the Lustre path and the run proceeds slowly rather than breaking.
#   - never write into the venv itself.
#
# USAGE
#   mpiexec -n <NODES> -ppn 1 --cpu-bind none --no-vni \
#       bash scripts/stage_venv_local.sh
#   # then, in the rank environment, only if the stage succeeded:
#   [ -f $VJEPA_VENV_LOCAL/.complete ] && export PYTHONPATH=$VJEPA_VENV_LOCAL:$PYTHONPATH

# NO `set -u` -- Lmod's init trips it ([[set-u-module-load-trap]]).
set -o pipefail

VENV=${VJEPA_VENV:-/flare/ModCon/ngetty/venvs/torchtune-pt213-xpu}
SITE=$VENV/lib/python3.12/site-packages
DEST=${VJEPA_VENV_LOCAL:-/tmp/vjepa_venv}
MANIFEST=${VJEPA_VENV_MANIFEST:-}
PKGS=${VJEPA_VENV_PKGS:-}
VJEPA_REPO_ROOT=${VJEPA_REPO_ROOT:-/lus/flare/projects/ModCon/ngetty/vjepa2}
HOST=$(hostname -s)

say () { echo "[stage_venv $HOST] $*"; }

[ -d "$SITE" ] || { say "no site-packages at $SITE -- not staging"; exit 0; }

# Already staged by a previous rung in this allocation? Staging is idempotent
# and the tree is read-only, so reuse it rather than paying again per rung.
if [ -f "$DEST/.complete" ]; then
    say "already staged at $DEST ($(cat "$DEST/.complete")) -- reusing"
    exit 0
fi

# Build into a private dir. Publishing is a rename, so a reader either sees no
# staged tree at all or sees a complete one -- never a partial one. Same reason
# the ladder publishes params.yaml this way.
TMP=$DEST.building.$$
rm -rf "$TMP" 2>/dev/null
mkdir -p "$TMP" || { say "cannot mkdir $TMP -- not staging"; exit 0; }

t0=$(date +%s)

# The manifest is a list of TOP-LEVEL package names (one per line), generated by
# scripts/gen_import_closure.py. Without one, fall back to the packages the
# closure is known to be dominated by. The fallback is deliberately a SUBSET and
# not "everything": staging the whole 5.2 GB tree into RAM to save 45 s is the
# wrong trade, and sys.path fallback makes a subset correct.
if [ -n "$PKGS" ] || { [ -n "$MANIFEST" ] && [ -r "$MANIFEST" ]; }; then
    # $VJEPA_VENV_PKGS (space-separated, from the environment) is the primary
    # channel and $VJEPA_VENV_MANIFEST (a path) the fallback. The env wins
    # because a manifest FILE has to live somewhere every node can read: /tmp is
    # node-local so only the head node sees it, and Lustre is the dependency
    # being removed. Job 8742102 shipped the manifest via /tmp and node 1
    # silently used the built-in list -- 19462 files staged against node 0's
    # 22933, with the two nodes of an A/B on different trees.
    if [ -n "$PKGS" ]; then
        printf '%s\n' $PKGS > "$TMP.manifest"
        MANIFEST=$TMP.manifest
    fi
    # A DIRECTORY list, not a file list: see the header. Names are appended to
    # $SITE/ here rather than in the manifest so the manifest stays venv-agnostic.
    #
    # DROP names that do not exist under $SITE, and say how many. rsync exits 23
    # on a missing source and would abort the whole stage; more importantly a
    # manifest generated against a different interpreter's site-packages (the
    # frameworks python resolves a different tree than the venv) would fail
    # entirely rather than partially, and the count below is what makes that
    # visible instead of silent.
    : > "$TMP.pkgs"; missing=0
    while IFS= read -r pkg; do
        [ -n "$pkg" ] || continue
        if [ -e "$SITE/$pkg" ]; then echo "$pkg" >> "$TMP.pkgs"
        else missing=$(( missing + 1 )); fi
    done < "$MANIFEST"
    say "staging $(wc -l < "$TMP.pkgs") packages from $MANIFEST ($missing not present under $SITE)"
    # Two rsync subtleties, both verified rather than assumed, and both silent
    # when wrong -- rc=0 with an empty or unimportable tree:
    #   - names stay RELATIVE to $SITE. --files-from implies -R, so absolute
    #     paths would reproduce the whole /lus/flare/... hierarchy under $TMP.
    #   - -r is EXPLICIT. --files-from turns OFF the -r that -a implies, so
    #     `rsync -a --files-from=<dirs>` creates the directories and copies
    #     nothing inside them. Measured: 0 files without -r, 2 with.
    rsync -a -r --files-from="$TMP.pkgs" "$SITE/" "$TMP/" 2>&1 | tail -3
    rc=$?
    rm -f "$TMP.pkgs" "$TMP.manifest"
else
    say "no manifest -- staging the measured dominant packages"
    rsync -a "$SITE"/{triton,torch,numpy,numpy.libs,sympy,timm,PIL,pillow.libs,yaml,torchvision,torchvision.libs,mpmath,cv2,opencv_python_headless.libs,decord,decord.libs} \
        "$TMP/" 2>&1 | tail -3
    rc=$?
fi

if [ "$rc" -ne 0 ]; then
    say "rsync rc=$rc -- NOT publishing, run will use Lustre"
    rm -rf "$TMP" 2>/dev/null
    exit 0
fi

# VERIFY BY IMPORTING THROUGH IT. Not a file count and not a byte comparison:
# both of the real failures (a missing dlopen'd .so, a missing binary under
# torch/bin) were invisible to any check that only compares what was copied
# against what was asked for. The only check that catches "the staged tree is
# subtly not usable" is to use it.
#
# Cheap enough to be unconditional -- it is one process on one node per rung,
# against ~45 s of import per rank. If it fails, the tree is never published and
# the run silently keeps the Lustre path.
#
# $VENV/bin/python, not bare `python`: the check is only meaningful against the
# interpreter the RANKS will use. Under mpiexec the stager may not inherit an
# activated venv's PATH, and a bare `python` that resolves elsewhere -- or not at
# all -- would fail the verify for a reason unrelated to the staged tree, which
# fails safe but silently gives up the whole optimization.
VERIFY_PY=$VENV/bin/python
[ -x "$VERIFY_PY" ] || VERIFY_PY=$(command -v python)
if [ -z "$VERIFY_PY" ]; then
    say "no interpreter to verify with -- NOT publishing, run will use Lustre"
    rm -rf "$TMP" 2>/dev/null
    exit 0
fi
if ! PYTHONPATH="$TMP:$VJEPA_REPO_ROOT" timeout 300 "$VERIFY_PY" -c \
        'import torch, numpy, torchvision, PIL, yaml, timm' > "$TMP.verify" 2>&1; then
    say "VERIFY FAILED -- NOT publishing, run will use Lustre. Tail:"
    tail -4 "$TMP.verify" | sed 's/^/    /'
    rm -rf "$TMP" "$TMP.verify" 2>/dev/null
    exit 0
fi
rm -f "$TMP.verify"

n=$(find "$TMP" -type f | wc -l)
mb=$(du -sm "$TMP" 2>/dev/null | cut -f1)
echo "$(date -Iseconds) files=$n mb=$mb" > "$TMP/.complete"

# Publish. rm -rf of any stale tree first: rename onto an existing DIRECTORY
# fails, unlike the file case.
rm -rf "$DEST" 2>/dev/null
if mv -T "$TMP" "$DEST" 2>/dev/null; then
    say "staged $n files / ${mb} MB in $(( $(date +%s) - t0 ))s -> $DEST"
else
    say "publish failed -- NOT staging, run will use Lustre"
    rm -rf "$TMP" 2>/dev/null
fi
exit 0
